import pandas as pd
df=pd.read_excel('Data/placement_predict_50k_Dataset.xlsx')
print(df.head())
print("========================================================================")
print(df.tail())
print("========================================================================")
print("number of rows and columns\n")
print(df.shape)
print("=================================================================")
print("Columns are \n", df.columns)
print("=================================================================")
print(df.info())
print("=================================================================")
print(df.describe())
print("=================================================================")
print(df.isnull().sum())
print("=================================================================")
print("duplicated values count : ",df.duplicated().sum())
print("=================================================================")
print(df["PlacementStatus"].value_counts())
